Change for the rockstar
JhaAman/whitespace_character pull request #59
Opened 2021-04-07 14:06 UTC by duykhang09

2021-04-07 14:29 UTC, garyszekely submitted a review, later dismissed

2021-04-10 14:52 UTC, k2nt commented on backend/api/services/user.py
> +            print(user)
remove this line

2021-04-10 14:53 UTC, k2nt commented on backend/backend/settings.py
> +    'REFRESH_TOKEN_LIFETIME': timedelta(days=20),
Set to 100 days

2021-04-10 14:54 UTC, k2nt requested changes
Move get_rockstar to user.py. Make minor changes as specified in comments

2021-04-11 12:28 UTC, closed without merging